---
title: "Untitled"
author: "Xintong Shi"
date: "12/4/2021"
output: html_document
---

```{r}
library(wordcloud)
library(RColorBrewer)
library(wordcloud2)
library(dplyr)
```
```{r}
positive = read.csv("628_tfidf_csv/positive.csv")
negative = read.csv("628_tfidf_csv/negative.csv")
one_two_stars = read.csv("628_tfidf_csv/df_fdist_1_2.csv")
four_five_stars = read.csv("628_tfidf_csv/df_fdist_4_5.csv")
```

```{r}
one_two_stars
```


```{r}
positive = positive[,-1]
negative = negative[,-1]
```

```{r}
positive.sorted = positive %>% arrange(desc(weight))
```
```{r}
positive.sorted
```

```{r}
positive.filtered = positive.sorted[-c(1,2,3,6,9,12,13,15,19,20,21,22,26,30,31,37,45,46),]
```


```{r}
wordcloud(words = positive.filtered$term, freq = positive.filtered$weight, min.freq = 0.001,           max.words=30, random.order=FALSE, rot.per=0.2,            colors=brewer.pal(4, "Dark2"))
```
```{r}
negative.sorted = negative %>% arrange(desc(weight))
```

```{r}
negative.sorted
```
```{r}
negative.filtered = negative.sorted[-c(1,3,6,12,14,15,16,20,25,26,27,28,29,31,32,33,34,35,47),]
```
```{r}
wordcloud(words = negative.filtered$term, freq = negative.filtered$weight, min.freq = 0.001,           max.words=30, random.order=FALSE, rot.per=0.2, colors=brewer.pal(4, "Dark2"))
```

```{r}
wordcloud(words = one_two_stars$Term, freq = one_two_stars$Frequency, min.freq = 0.001,           max.words=40, random.order=FALSE, rot.per=0.2, colors=brewer.pal(4, "Dark2"))
```

```{r}
wordcloud(words = four_five_stars$Term, freq = four_five_stars$Frequency, min.freq = 0.001,           max.words=40, random.order=FALSE, rot.per=0.2, colors=brewer.pal(4, "Dark2"))
```

